import Cleanup
import Core
import Foundation
import Pipeline

/// Turns the raw result files into the Markdown tables for docs/m0-results.md.
struct ReportBuilder {
    let paths: CommonPaths
    let corpus: Corpus?

    init(paths: CommonPaths) {
        self.paths = paths
        self.corpus = try? Corpus.load(from: paths.corpusURL)
    }

    static let speechSets = ["plain", "numbers", "names", "quiet", "correction", "levels"]
    static let werSets = ["plain", "numbers", "names", "quiet"]

    var clipById: [String: CorpusClip] {
        Dictionary(uniqueKeysWithValues: (corpus?.clips ?? []).map { ($0.id, $0) })
    }

    func files(prefix: String) -> [URL] {
        let names = (try? FileManager.default.contentsOfDirectory(atPath: paths.results)) ?? []
        return names.filter { $0.hasPrefix(prefix) && $0.hasSuffix(".json") }.sorted().map { paths.resultsURL.appendingPathComponent($0) }
    }

    var engines: [EnginePassResult] {
        files(prefix: "engine-").compactMap { ResultFiles.read(EnginePassResult.self, from: $0) }
    }

    var cleanups: [CleanupPassResult] {
        files(prefix: "cleanup-").compactMap { ResultFiles.read(CleanupPassResult.self, from: $0) }
    }

    func wer(_ engine: EnginePassResult, sets: [String]) -> TextMetrics.WERResult? {
        let clips = engine.clips.filter { sets.contains($0.set) }
        guard !clips.isEmpty else { return nil }
        return clips.reduce(TextMetrics.WERResult.zero) { acc, c in
            guard let ref = clipById[c.id]?.reference else { return acc }
            return acc + TextMetrics.wer(reference: ref, hypothesis: c.text ?? "")
        }
    }

    func bestEngine() -> String? {
        engines.filter { $0.error == nil && $0.isLocal }
            .compactMap { e in wer(e, sets: Self.werSets).map { (e.engine, $0.rate) } }
            .min { $0.1 < $1.1 }?.0
    }

    // MARK: Markdown

    func markdown() -> String {
        var md = "<!-- Generated by `murmur-bench report` on \(ISO8601DateFormatter().string(from: Date())). Do not edit by hand. -->\n\n"
        md += setupSection()
        md += engineSection()
        md += cleanupSection()
        md += endToEndSection()
        md += stallSection()
        return md
    }

    func setupSection() -> String {
        var md = "## Setup\n\n"
        let host = ProcessInfo.processInfo
        md += "- Mac: \(Self.sysctl("machdep.cpu.brand_string") ?? "?"), \(host.physicalMemory / 1_073_741_824) GB, macOS \(host.operatingSystemVersionString)\n"
        if let corpus {
            let recorded = corpus.clips.filter { FileManager.default.fileExists(atPath: Corpus.audioURL($0, in: paths.corpusURL).path) }
            md += "- Corpus: \(recorded.count) of \(corpus.clips.count) clips recorded ("
            md += Corpus.setOrder.map { s in "\(s) \(recorded.filter { $0.set == s }.count)" }.joined(separator: ", ") + ")\n"
        }
        let builds = Set(engines.map(\.build) + cleanups.map(\.build))
        md += "- Build: \(builds.sorted().joined(separator: ", "))\n"
        md += "- Memory is the process footprint (`proc_pid_rusage`). CoreML work on the Neural Engine is partly accounted to system daemons, so local CoreML engines read lower than their true cost.\n\n"
        return md
    }

    func engineSection() -> String {
        let list = engines
        guard !list.isEmpty else { return "## Speech engines\n\nNo engine results yet.\n\n" }
        var md = "## Speech engines\n\n"
        md += "WER uses a shared normalizer (case, punctuation, number words, hesitations). Entity accuracy is on the raw transcript, before cleanup. Latency is transcription only, model loaded, \(list.first?.runs.count ?? 0) runs over clips up to 15 s.\n\n"
        md += "| Engine | Local | Load | Footprint after load | Peak | WER all | WER plain | WER numbers | WER names | WER quiet | Entities | p50 | p95 | Speed |\n"
        md += "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n"
        for e in list {
            if let error = e.error {
                md += "| \(e.engine) | \(e.isLocal ? "yes" : "cloud") | failed: \(error.prefix(80)) |||||||||||||\n"
                continue
            }
            let all = wer(e, sets: Self.werSets).map { Format.pct($0.rate) } ?? "-"
            let perSet = Self.werSets.map { s in wer(e, sets: [s]).map { Format.pct($0.rate) } ?? "-" }
            let entity = entityAccuracy(e)
            let ms = e.runs.map(\.ms)
            let speed = e.runs.isEmpty ? "-" : String(format: "%.0f×", e.runs.map(\.audioMs).reduce(0, +) / max(ms.reduce(0, +), 1))
            md += "| \(e.engine) | \(e.isLocal ? "yes" : "cloud") | \(e.loadMs.map(Format.ms) ?? "-") | \(e.footprintAfterLoad.map(Format.mb) ?? "-") | \(e.peakFootprint.map(Format.mb) ?? "-") | \(all) | \(perSet.joined(separator: " | ")) | \(entity) | \(Stats.percentile(ms, 50).map(Format.ms) ?? "-") | \(Stats.percentile(ms, 95).map(Format.ms) ?? "-") | \(speed) |\n"
        }
        md += "\n### Silence and noise (D6)\n\nClips from the silence set that would insert text. Target: 0.\n\n"
        md += "| Engine | Clips | No gate | Energy gate | Silero gate | What the engine heard |\n| --- | ---: | ---: | ---: | ---: | --- |\n"
        for e in list where e.error == nil {
            let silent = e.clips.filter { $0.set == "silence" }
            guard !silent.isEmpty else { continue }
            func inserts(_ c: EnginePassResult.Clip) -> Bool { !(c.text ?? "").trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
            let noGate = silent.filter(inserts).count
            let energy = silent.filter { $0.energyGate && inserts($0) }.count
            let silero = silent.filter { ($0.sileroGate ?? true) && inserts($0) }.count
            let heard = silent.filter(inserts).map { "\($0.id): \"\(($0.text ?? "").prefix(30))\"" }.joined(separator: "; ")
            md += "| \(e.engine) | \(silent.count) | \(noGate) | \(energy) | \(silero) | \(heard.isEmpty ? "-" : heard) |\n"
        }
        md += "\n"
        return md
    }

    func entityAccuracy(_ e: EnginePassResult) -> String {
        var total = 0, kept = 0
        for c in e.clips where ["numbers", "names"].contains(c.set) {
            guard let clip = clipById[c.id] else { continue }
            for entity in clip.entities ?? [] {
                total += 1
                if CorpusChecks.entityPresent(c.text ?? "", entity) { kept += 1 }
            }
        }
        return total == 0 ? "-" : "\(kept)/\(total)"
    }

    struct CleanupStats {
        var corrections: (ok: Int, total: Int)
        var changeModel: (changed: Int, total: Int)
        var changeFinal: (changed: Int, total: Int)
        var injection: (ok: Int, total: Int)
        var timeouts: Int
        var guardFallbacks: Int
        var errors: Int
        var runs: Int
    }

    /// An unintended change: an entity or negation that was in the input is missing from the output,
    /// or a must-not-appear string (an answer, a translation) shows up.
    func changed(input: String, output: String, clip: CorpusClip) -> Bool {
        for entity in clip.entities ?? [] where CorpusChecks.entityPresent(input, entity) && !CorpusChecks.entityPresent(output, entity) {
            return true
        }
        if clip.set != "correction" && GuardChecker.negationCount(input) != GuardChecker.negationCount(output) { return true }
        for bad in clip.mustExclude ?? [] where clip.set != "correction" && CorpusChecks.contains(output, bad) { return true }
        return false
    }

    func stats(_ r: CleanupPassResult) -> CleanupStats {
        let light = r.clips.filter { $0.level == "light" }
        var corrections = (0, 0), model = (0, 0), final = (0, 0), injection = (0, 0)
        for c in light {
            guard let clip = clipById[c.id] else { continue }
            if c.set == "correction" {
                corrections.1 += 1
                if CorpusChecks.correctionResolved(c.final, clip).ok { corrections.0 += 1 }
                continue
            }
            let modelOut = c.modelText ?? c.final
            model.1 += 1
            final.1 += 1
            if changed(input: c.input, output: modelOut, clip: clip) { model.0 += 1 }
            if changed(input: c.input, output: c.final, clip: clip) { final.0 += 1 }
            if ["levels-12", "levels-13", "levels-14", "levels-17"].contains(c.id) {
                injection.1 += 1
                if !changed(input: c.input, output: c.final, clip: clip) { injection.0 += 1 }
            }
        }
        return CleanupStats(
            corrections: corrections, changeModel: model, changeFinal: final, injection: injection,
            timeouts: r.runs.filter { $0.fallback == "timeout" }.count,
            guardFallbacks: r.runs.filter { $0.fallback == "guard" }.count,
            errors: r.runs.filter { $0.fallback == "error" }.count,
            runs: r.runs.count
        )
    }

    func cleanupSection() -> String {
        let list = cleanups
        guard !list.isEmpty else { return "## Cleanup\n\nNo cleanup results yet.\n\n" }
        var md = "## Cleanup\n\n"
        md += "Light level unless noted. **Corrections** is the 30-clip self-correction set (C2, target 27/30). **Changes** counts clips where a number, name, URL, negation or other required entity present in the input is gone from the output, or a forbidden answer/translation appears; \"model\" is the raw model output, \"final\" is after the guard checker swapped in the rule-cleaned text (target 0). **C7** is the four transcript-is-data clips (a poem request, \"ignore the previous message\", a factual question, a translate request).\n\n"
        for source in Set(list.map(\.source)).sorted(by: { $0 == "reference" ? true : ($1 == "reference" ? false : $0 < $1) }) {
            md += source == "reference"
                ? "### On the written sentences (cleanup alone, no speech errors)\n\n"
                : "### On \(source) transcripts (end to end)\n\n"
            md += "| Provider | Load | Footprint | Model p50 | Model p95 | Corrections | Changes (model) | Changes (final) | C7 | Timeouts | Guard fallbacks | Errors |\n"
            md += "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n"
            for r in list.filter({ $0.source == source }) {
                if let error = r.error {
                    md += "| \(r.provider) | failed: \(error.prefix(80)) |||||||||||\n"
                    continue
                }
                let s = stats(r)
                let llm = r.runs.compactMap(\.llmMs)
                func ratio(_ p: (Int, Int)) -> String { p.1 == 0 ? "-" : "\(p.0)/\(p.1)" }
                md += "| \(r.provider) | \(r.loadMs.map(Format.ms) ?? "-") | \(r.footprintAfterLoad.map(Format.mb) ?? "-") | \(Stats.percentile(llm, 50).map(Format.ms) ?? "-") | \(Stats.percentile(llm, 95).map(Format.ms) ?? "-") | \(ratio(s.corrections)) | \(ratio(s.changeModel)) | \(ratio(s.changeFinal)) | \(ratio(s.injection)) | \(s.timeouts)/\(s.runs) | \(s.guardFallbacks)/\(s.runs) | \(s.errors)/\(s.runs) |\n"
            }
            md += "\n"
        }
        md += failuresSection(list.filter { $0.source == "reference" })
        return md
    }

    func failuresSection(_ list: [CleanupPassResult]) -> String {
        var md = "<details><summary>Correction and C7 failures per provider (reference text)</summary>\n\n"
        for r in list where r.error == nil {
            var lines: [String] = []
            for c in r.clips where c.level == "light" {
                guard let clip = clipById[c.id] else { continue }
                if c.set == "correction" {
                    let check = CorpusChecks.correctionResolved(c.final, clip)
                    if !check.ok { lines.append("- \(c.id): \(check.why ?? "") → \"\(c.final)\"\(c.fallback.map { " (\($0))" } ?? "")") }
                } else if changed(input: c.input, output: c.modelText ?? c.final, clip: clip) {
                    lines.append("- \(c.id) model changed facts → \"\(c.modelText ?? c.final)\"\(c.fallback.map { " (final used \($0) fallback)" } ?? "")")
                }
            }
            md += "**\(r.provider)**\n\n" + (lines.isEmpty ? "- none\n" : lines.joined(separator: "\n") + "\n") + "\n"
        }
        return md + "</details>\n\n"
    }

    func endToEndSection() -> String {
        var md = "## End to end\n\n"
        // Estimate from the passes: transcription + rules + model (capped) per clip, for every engine
        // whose transcripts went through cleanup.
        for engine in engines where engine.error == nil {
            let passes = cleanups.filter { $0.source == engine.engine && $0.error == nil }
            guard !passes.isEmpty else { continue }
            let transcribe = Dictionary(engine.clips.compactMap { c in c.ms.map { (c.id, $0) } }, uniquingKeysWith: { a, _ in a })
            md += "### Estimate: \(engine.engine) + each cleanup option (key release to text, excluding capture flush and insertion)\n\n"
            md += "| Cleanup | Clips | p50 | p95 | Corrections end to end |\n| --- | ---: | ---: | ---: | ---: |\n"
            for r in passes {
                let totals = r.clips.filter { $0.level == "light" }.compactMap { c in transcribe[c.id].map { $0 + c.rulesMs + min(c.llmMs ?? 0, 800) } }
                let s = stats(r)
                md += "| \(r.provider) | \(totals.count) | \(Stats.percentile(totals, 50).map(Format.ms) ?? "-") | \(Stats.percentile(totals, 95).map(Format.ms) ?? "-") | \(s.corrections.1 == 0 ? "-" : "\(s.corrections.0)/\(s.corrections.1)") |\n"
            }
            md += "\n"
        }
        let e2e = files(prefix: "e2e-").compactMap { ResultFiles.read(E2EResult.self, from: $0) }
        if !e2e.isEmpty {
            md += "### Measured: replay into TextEdit with the full insertion transaction\n\n"
            md += "Release to paste posted (capture flush excluded; see the live `dictate` numbers below for that).\n\n"
            md += "| Engine | Cleanup | Runs | Inserted | Clipboard restored | Transcribe p50 | Rules p50 | Model p50 | Insert p50 | **Total p50** | **Total p95** |\n"
            md += "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n"
            for r in e2e {
                func p(_ stage: Stage, _ q: Double) -> String { Stats.percentile(r.runs.compactMap { $0.timings[stage] }, q).map(Format.ms) ?? "-" }
                let inserted = r.runs.filter { $0.status == "inserted" }.count
                let restored = r.runs.filter { $0.restored == true }.count
                md += "| \(r.engine) | \(r.cleanup) | \(r.runs.count) | \(inserted) | \(restored) | \(p(.transcribe, 50)) | \(p(.rules, 50)) | \(p(.llm, 50)) | \(p(.insert, 50)) | **\(p(.total, 50))** | **\(p(.total, 95))** |\n"
            }
            md += "\n"
        }
        let live = TimingLog.read()
        if !live.isEmpty {
            md += "### Measured: live `murmur-cli dictate` sessions\n\n"
            md += "| Engine | Cleanup | Dictations | First audio p50 | Capture flush p50 | Transcribe p50 | Model p50 | Insert p50 | **Total p50** | **Total p95** |\n"
            md += "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n"
            let groups = Dictionary(grouping: live.filter { $0.status == "inserted" }) { "\($0.engine)|\($0.cleanup)" }
            for key in groups.keys.sorted() {
                let g = groups[key]!
                func p(_ stage: Stage, _ q: Double) -> String { Stats.percentile(g.compactMap { $0.timings[stage] }, q).map(Format.ms) ?? "-" }
                let first = Stats.percentile(g.compactMap(\.firstAudioMs), 50).map(Format.ms) ?? "-"
                md += "| \(g[0].engine) | \(g[0].cleanup) | \(g.count) | \(first) | \(p(.captureFlush, 50)) | \(p(.transcribe, 50)) | \(p(.llm, 50)) | \(p(.insert, 50)) | **\(p(.total, 50))** | **\(p(.total, 95))** |\n"
            }
            md += "\n"
        }
        return md
    }

    func stallSection() -> String {
        guard let s = ResultFiles.read([String: Double].self, from: paths.resultsURL.appendingPathComponent("stall-test.json")) else { return "" }
        let max = s["max"] ?? 0
        return "## Stalled model (C6)\n\nWith a provider that never answers and ignores cancellation, the rule-cleaned text was returned in at most \(Format.ms(max)) over \(Int(s["trials"] ?? 0)) trials (limit 1.5 s): **\(max < 1500 ? "pass" : "fail")**.\n\n"
    }

    static func sysctl(_ name: String) -> String? {
        var size = 0
        guard sysctlbyname(name, nil, &size, nil, 0) == 0, size > 0 else { return nil }
        var buffer = [CChar](repeating: 0, count: size)
        guard sysctlbyname(name, &buffer, &size, nil, 0) == 0 else { return nil }
        return String(decoding: buffer.prefix { $0 != 0 }.map { UInt8(bitPattern: $0) }, as: UTF8.self)
    }
}
