import AppKit
import Foundation

/// Every item and every type on the pasteboard, captured as raw data so any content survives:
/// plain and rich text, images, files, PDF, RTFD, audio.
public struct PasteboardSnapshot: Sendable, Equatable {
    public struct Item: Sendable, Equatable {
        public var types: [(String, Data)]

        public init(_ types: [(String, Data)]) { self.types = types }

        public static func == (a: Item, b: Item) -> Bool {
            a.types.count == b.types.count && zip(a.types, b.types).allSatisfy { $0.0 == $1.0 && $0.1 == $1.1 }
        }
    }

    public var items: [Item]
    public var changeCount: Int

    public init(items: [Item], changeCount: Int) {
        self.items = items
        self.changeCount = changeCount
    }

    public var isEmpty: Bool { items.isEmpty }
}

/// The parts of NSPasteboard the insertion transaction uses, so it can run against a fake in tests.
public protocol Pasteboarding: AnyObject, Sendable {
    var changeCount: Int { get }
    func snapshot() -> PasteboardSnapshot
    /// Replaces the contents with `text` plus marker types. Returns the new change count.
    func writeTranscript(_ text: String, markers: [String]) -> Int
    /// Replaces the contents with the snapshot's items.
    func restore(_ snapshot: PasteboardSnapshot)
    func string() -> String?
}

public enum PasteboardMarkers {
    /// nspasteboard.org conventions. Clipboard managers skip transient and concealed content.
    public static let transient = "org.nspasteboard.TransientType"
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    public static let source = "org.nspasteboard.source"

    public static let all = [transient, concealed, autoGenerated]
}

public final class SystemPasteboard: Pasteboarding, @unchecked Sendable {
    let board: NSPasteboard

    public init(_ board: NSPasteboard = .general) {
        self.board = board
    }

    public var changeCount: Int { board.changeCount }

    public func snapshot() -> PasteboardSnapshot {
        let count = board.changeCount
        let items = (board.pasteboardItems ?? []).map { item in
            PasteboardSnapshot.Item(item.types.compactMap { type in
                item.data(forType: type).map { (type.rawValue, $0) }
            })
        }
        return PasteboardSnapshot(items: items, changeCount: count)
    }

    public func writeTranscript(_ text: String, markers: [String]) -> Int {
        board.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for marker in markers {
            item.setData(Data(), forType: NSPasteboard.PasteboardType(marker))
        }
        if let bundle = Bundle.main.bundleIdentifier {
            item.setString(bundle, forType: NSPasteboard.PasteboardType(PasteboardMarkers.source))
        }
        board.writeObjects([item])
        return board.changeCount
    }

    public func restore(_ snapshot: PasteboardSnapshot) {
        board.clearContents()
        guard !snapshot.items.isEmpty else { return }
        let items = snapshot.items.map { saved -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in saved.types {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        board.writeObjects(items)
    }

    public func string() -> String? { board.string(forType: .string) }
}
